version: "3"

services:
    web_charts:
        build: .
        container_name: temp_chart
        network_mode: host
        volumes:
            - ./app:/app
        environment:
            TZ: "Europe/London"
        command: python /app/app.py
        secrets:
            - un
            - pw
            - host

secrets:
    un:
        file: ./secrets/un
    pw:
        file: ./secrets/pw
    host:
        file: ./secrets/host